### PR TITLE
Add property to stop filter chain after successful authentication

### PR DESCRIPTION
**Pull request by alt250**
Fix for https://github.com/spring-projects/spring-security-kerberos/issues/96

### CODE REVIEW

**Comment by alt250** [comment]
I have signed and agree to the terms of the SpringSource Individual Contributor License Agreement.

**Comment by rwinch** [comment]
Thanks for the PR and sorry for the delay. If you can update the PR to resolve the merge issues, we can get this merged into master

**Comment by SergeyKlimchuk** [comment]
I think this should fix #189 too

**Comment by rwinch** [comment]
@alt250 Thank you for the PR. This is now merged into main

Thank you for [pointing](https://github.com/spring-projects/spring-security-kerberos/pull/97#issuecomment-2131189833) me to the additional duplicate @SergeyKlimchuk

**Pull request closed without merging**
