### PR TITLE
Correct a typo in appendix.adoc

### PR DESCRIPTION
**Pull request by qwefgh90**
correct a typo. "send" should be "sent".

### CODE REVIEW

**Comment by qwefgh90** [comment]
Additionally, "have" should be "gave" .

**Comment by jzheaux** [comment]
Thanks, @qwefgh90! Would you mind [squashing your commits](https://github.com/spring-projects/spring-security-kerberos/blob/master/CONTRIBUTING.md#squash-commits), please?

**Comment by qwefgh90** [comment]
@jzheaux 
I squashed and push forcely into origin/patch-1. Is this what you meant?

**Comment by rwinch** [comment]
Thanks for the PR @qwefgh90 This is now merged into main

**Pull request closed without merging**
